import type { NextPage } from "next";
import Head from "next/head";
import Article from "../components/article";
import Section from "../components/section";
import Showcase from "../components/showcase";
import styles from "./../styles/main.module.scss";

const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Design and Build Web apps with Etsh</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className={styles.hero}>
				<h2 className={styles.name}>Etsh</h2>
				<h3>
					Hi, I am a{" "}
					<span className={styles.design}>UX Designer</span> &{" "}
					<span className={styles.develop}>NextJs Developer</span>{" "}
					from Cairo
				</h3>
			</div>
			<Showcase />
			<Section title="About">
				<p>
					I develop and design applications for the web. I’m
					passionate about web apps that provides a great experience
					for users.
				</p>
			</Section>
			<Section title="Writing">
				<div>
					<Article title="Title" description="Description" />
				</div>
			</Section>
			<div>
				<h4>Connect</h4>
				<div>
					<div>Email</div>
					<div>Twitter</div>
					<div>Github</div>
				</div>
			</div>
		</div>
	);
};

export default Home;
